apiVersion: v1
kind: Service
metadata:
  name: {{ include "socks5-reverse-proxy.fullname" . }}
spec:
  ports:
  - name: "tcp-{{ .Values.appName }}"
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "socks5-reverse-proxy.fullname" . }}
